name = "my-personal-project-api-3"
client_id = "899f1abe2e998ef21d00423227e47ceb"
application_url = "https://myaistore-5.myshopify.com"
embedded = false

[access_scopes]
scopes = "read_products,write_products,read_content,write_content,read_themes,write_themes,read_script_tags,write_script_tags,read_orders,write_orders"

[auth]
redirect_urls = [
  "http://localhost:3456/callback"
]

[webhooks]
api_version = "2026-04"
